### ISSUE TITLE
Passing props through onClick

### ISSUE THREAD

**Issue by Jorrit2002** [nak1b/react-native-composite-navigation#1]
Could you tell me how I can pass props and use those in a container when I'm using:
            onPress={() => this.props.onClick({ key: 'contactList', title: 'Contacts' })}

**Comment by nak1b** [comment]
@Jorrit2002  i am not sure what you are trying to do. can you elaborate more?

**Comment by Jorrit2002** [comment]
Sorry, I forgot about this question. I got it working by doing this:

`onPress={() => this.props.onClick({ key: 'contactList', title: 'Contacts', props: props})}`

```
const MeteorContainer = Meteor.createContainer((props) => {
 const { prop1, prop2 } = props
  return {
    reviews: //Meteor call using props here
  };
}, App);

```
