### ISSUE TITLE
use StateUtils.jumpTo(),it will re-render the prevscenes.

### ISSUE THREAD

**Issue by sunny635533** [nak1b/react-native-composite-navigation#3]
Hello,when i jump between the different tabs and use StateUtils.jumpTo(),it will re-render the prescenes ,then it jumped that tab. I don't know why use jumpTo(),all the secenes will re-redner ervey time when i click another tab's secene.

**Comment by nak1b** [comment]
Hey @sunny635533 this example does not use NavigationStack per tab Basically you should use  NavigationStack per Tab to not re-render on changing Tabs. You should initially set routes for those tabs and navigate between them.

I created this repo when Navigation was still experimental in react-native. You should use this [react navigation](https://reactnavigation.org/) solution instead.

**Comment by sunny635533** [comment]
@nak1b thanks,i am reading it now.
